### ISSUE TITLE
Old version

### ISSUE THREAD

**Issue by bulbulogludemir** [kursatabayli/ChatGPT_apk#1]
Can you update the app version please, thanks!

**Comment by kursatabayli** [comment]
Merhaba,
Kullandığım emülatörler üzerinde herhangi bir sorun görüntüleyemiyorum. Kontrollerim sonucu programda olağan bir hata bulamadım. Eğer yaşadığınız sorunla ilgili daha fazla detay verebilir veya ekran görüntüsü paylaşabilirseniz elimden geleni yaparım.
________________________________
Gönderen: Demir Bülbüloğlu ***@***.***>
Gönderildi: 7 Kasım 2024 Perşembe 21:06
Kime: kursatabayli/ChatGPT_apk ***@***.***>
Bilgi: Subscribed ***@***.***>
Konu: [kursatabayli/ChatGPT_apk] Old version (Issue #1)


Can you update the app version please, thanks!
